### ISSUE TITLE
幫 QQ

### ISSUE THREAD

**Issue by Ice1187** [ARui-TW/linne_makeup_platform#42]
**Describe the bug**
A exhausted CS student, also a website developer.

**To Reproduce**
1. Ask ARui-TW to write a website for you.
2. He's so kind to accepts the request without taking any money.
3. ARui-TW is such a kind CS student.
4. See him exhausted.

**Expected behavior**
A exhausted ARui-TW.

**Additional Context**
GitHub is developers' Facebook, so I decided to leave my comment here.

**Comment by Ice1187** [comment]
Also give him a star for his hard and excellent work, also for his kindness.

**Comment by ARui-TW** [comment]
I actually get paid for this project. No more free service :)
Since you get the exhausted ARui as you expected, I'll close this issue. And thank you for your star XDD
