### ISSUE TITLE
Horizon scrolling

### ISSUE THREAD

**Issue by ARui-TW** [ARui-TW/linne_makeup_platform#43]
**Describe the bug**
The website can scroll horizontally, which shouldn't.

**To Reproduce**
1. Open the website
2. It can scroll horizontally!

**Expected behavior**
It shouldn't scroll horizontally since the content's width can fit in the browsing window.

**Additional context**
It only happens on the desktop web browser. Maybe it's the picture on the left-hand side causing this problem?

**Comment by 35538785** [comment]
Fixed.
