### ISSUE TITLE
Certification application is not functional.

### ISSUE THREAD

**Issue by 35538785** [ARui-TW/linne_makeup_platform#45]
**Describe the bug**
No response appear after press the certification application button.

**To Reproduce**

1. Go to #/Certificate
2. Click on '送出'
3. No response 

**Expected behavior**
An email should be sent after pressing the certification application button.

**Screenshots**
![image](https://user-images.githubusercontent.com/56823118/191504298-357b710f-8dbc-4aef-8305-b03073fed672.png)

**Additional context**
All certification application pages have the same problem.

**Comment by 35538785** [comment]
Error report.

**Screenshots**
![image](https://user-images.githubusercontent.com/56823118/192153150-3c3fd33d-76aa-4b92-b4d2-67b2434b0517.png)

**Comment by ARui-TW** [comment]
@35538785 Is this still unfixed?

**Comment by 35538785** [comment]
Fixed, thank you!
