### ISSUE TITLE
Profession account application without login

### ISSUE THREAD

**Issue by 35538785** [ARui-TW/linne_makeup_platform#46]
**Describe the bug**
I can only apply profession account when login.

**To Reproduce**
1. Go to expert/register without login
2. Click on '註冊'
3. No response

**Expected behavior**
We should apply a profession account without login.

**Screenshots**
![image](https://user-images.githubusercontent.com/56823118/191505884-dcd8e783-eea7-4626-92cb-bb3e708c5682.png)

**Comment by ARui-TW** [comment]
This is a back-end error. Fixed in back-end
