### ISSUE TITLE
排版

### ISSUE THREAD

**Issue by lily551133** [ARui-TW/linne_makeup_platform#51]
4個覺得有些詭異的排版
若是能調整 再麻煩處理

1.絕對分數
是否可4張照片都放置在灰色框框中
或是將底圖放大4張照片都可包含 刪除灰色框框
![image](https://user-images.githubusercontent.com/67411179/191990113-c0e91767-0a06-4586-b0df-f7cb1497e2cf.png)

2.相對分數
難以判斷和下一組的btn可否致中在灰色框框
![image](https://user-images.githubusercontent.com/67411179/191990683-7a864eb6-9219-4fcd-aa1a-fd247b7aa9e7.png)

3.夥伴團隊內文
是否文字和圖片可以不要100%繼承寬度 感覺可以留些白邊 
壓迫改比較小 我覺得可以80%
![image](https://user-images.githubusercontent.com/67411179/191990779-a10eacc5-dd83-4e34-97ff-7d3355197d7f.png)

4.相對分數和絕對分數中
證書申請 個人帳號 回首頁 
這三個btn可以寬度對其灰色框框 然後三個至中對其排列嗎
ex: justify-content: space-around
![image](https://user-images.githubusercontent.com/67411179/191990852-d0b1c1fd-7fce-4867-8877-5fd879a7c8f8.png)
https://blog.csdn.net/hunhun1122/article/details/78591103
![image](https://user-images.githubusercontent.com/67411179/191992904-3262f70c-53c9-43a5-ad9c-9365831ffcea.png)

**Comment by ARui-TW** [comment]
The "weird" design in 1 and 2 is actually following the design that I get.

![image](https://user-images.githubusercontent.com/66272957/192144956-c17895b0-2174-4abf-b0a6-8e26cc8e150b.png)

Also, the three buttons in absolute score and relative score are already using `space-around`. You can take a look at [here](https://github.com/ARui-TW/linne_makeup_platform/blob/staging/src/views/MakeupScore/Relative.vue#L64) and [here](https://github.com/ARui-TW/linne_makeup_platform/blob/staging/src/views/MakeupScore/Absolute.vue#L67). The class `justify-around` means `justify-content: space-around` in [tailwindcss](https://tailwindcss.com/docs/justify-content). However, if you haven't used tailwind before, you can still check the CSS of this content by [Chrome DevTools](https://developer.chrome.com/docs/devtools/) and get the same result. The main problem is that the width of this div is too small for them, I'm sorry for not noticing it. 

![image](https://user-images.githubusercontent.com/66272957/192147587-33b77fce-714b-4f6c-b251-52899a4752f7.png)

Moreover, I recommended [this tutorial](https://www.casper.tw/css/2017/07/21/css-flex/) for flex instead blog from China. Not only this tutorial is clearer, but it uses CodePen to demonstrate the result, in this way you can learn by editing the code and observing the result.

Sorry for my poor English writing, if you have any other questions, you are welcome to comment below.

By the way, these issue is all fixed.
